// Roverland Voyage — sample trip data for the website UI kit.
// NOTE: imagery uses royalty-free Unsplash photography as PLACEHOLDERS — swap for
// licensed Roverland route photography in production. (Flagged in the system caveats.)
window.RV_DATA = {
  trips: [
    {
      id: "spiti",
      title: "Spiti Valley Wonder Drive",
      location: "Himachal Pradesh",
      region: "Mountain",
      days: "6 days · 5 nights",
      price: "₹62,000",
      rating: 4.9,
      badge: "Surprise inside",
      badgeTone: "teal",
      image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1100&q=80&auto=format&fit=crop",
      blurb: "Cold desert, prayer flags and the highest villages on earth — a high-altitude ribbon of wow.",
      itinerary: [
        ["Day 1", "Shimla → Narkanda", "Apple country & a sunset ridge no map will show you."],
        ["Day 2", "Narkanda → Kalpa", "The Kinnaur Kailash range wakes up in gold."],
        ["Day 3", "Kalpa → Tabo", "Ancient monastery, a thousand-year-old hush."],
        ["Day 4", "Tabo → Kaza", "★ A surprise riverside breakfast we won't spoil."],
        ["Day 5", "Kaza → Chandratal", "Camp beside the Moon Lake under a sky on fire."],
        ["Day 6", "Chandratal → Manali", "Cross Kunzum La and descend into green."],
      ],
    },
    {
      id: "konkan",
      title: "Konkan Coast Cruise",
      location: "Maharashtra & Goa",
      region: "Coastal",
      days: "5 days · 4 nights",
      price: "₹48,000",
      rating: 4.8,
      badge: "Bestseller",
      badgeTone: "brand",
      image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1100&q=80&auto=format&fit=crop",
      blurb: "Palm-lined curves, hidden coves and seafood at golden hour. The Arabian Sea on your right the whole way.",
      itinerary: [
        ["Day 1", "Mumbai → Alibaug", "First toes in the sand by lunch."],
        ["Day 2", "Alibaug → Ganpatipule", "★ A detour to a beach you'll want to keep secret."],
        ["Day 3", "Ganpatipule → Tarkarli", "Backwaters, dolphins, and a clear-water swim."],
        ["Day 4", "Tarkarli → Palolem", "Cross into Goa as the light turns amber."],
        ["Day 5", "Palolem → Panaji", "Old-town cafés and a slow farewell."],
      ],
    },
    {
      id: "rann",
      title: "Rann of Kutch Mirage Run",
      location: "Gujarat",
      region: "Desert",
      days: "4 days · 3 nights",
      price: "₹39,000",
      rating: 4.7,
      badge: "Full moon special",
      badgeTone: "warning",
      image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1100&q=80&auto=format&fit=crop",
      blurb: "A white salt horizon that never ends, and a moon so bright it casts shadows on the desert.",
      itinerary: [
        ["Day 1", "Ahmedabad → Bhuj", "Handicraft villages and a warm Kutchi welcome."],
        ["Day 2", "Bhuj → White Rann", "★ Moonrise over the salt flats. No words."],
        ["Day 3", "Kalo Dungar", "The Black Hill — the only high point for miles."],
        ["Day 4", "Bhuj → Ahmedabad", "One last chai before the road home."],
      ],
    },
    {
      id: "meghalaya",
      title: "Meghalaya Cloud Roads",
      location: "North-East India",
      region: "Forest",
      days: "7 days · 6 nights",
      price: "₹71,000",
      rating: 5.0,
      badge: "New route",
      badgeTone: "teal",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1100&q=80&auto=format&fit=crop",
      blurb: "Living-root bridges, the cleanest village on earth, and roads that disappear into cloud.",
      itinerary: [
        ["Day 1", "Guwahati → Shillong", "The Scotland of the East unfolds."],
        ["Day 2", "Shillong → Cherrapunji", "Waterfalls taller than you can photograph."],
        ["Day 3", "Double-Decker Trek", "★ A surprise picnic at a turquoise pool."],
        ["Day 4", "Cherrapunji → Dawki", "Boats that float on glass-clear water."],
        ["Day 5", "Mawlynnong", "Asia's cleanest village, by design."],
        ["Day 6", "Krang Suri Falls", "One more impossible blue."],
        ["Day 7", "Return to Guwahati", "Carry the clouds home with you."],
      ],
    },
  ],
  values: [
    ["Wonder First", "Every journey begins with the pursuit of awe."],
    ["Curated Freedom", "Freedom without friction — meticulously planned, hassle-free."],
    ["Surprise & Delight", "Thoughtful surprises woven into every mile."],
    ["Soulful Connections", "More than destinations — we seek stories."],
  ],
  steps: [
    ["01", "Pick your wow", "Choose a curated route — or tell us the feeling you're chasing."],
    ["02", "We craft the map", "A meticulous, surprise-laced itinerary lands in your inbox."],
    ["03", "Drive into it", "You take the wheel. We handle everything else."],
  ],
};
